"""Bilingual UI string table for the HTML report. See docs/architecture/06-html-report.md.

Both language dicts must define the exact same key set (tests/report/test_strings.py).
The template references keys only (strings.*), never literal text (FR-005/FR-019).
"""

from __future__ import annotations

STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "report_title": "Test Report",
        "dark_mode_toggle": "Dark mode",
        "no_value_placeholder": "—",
        "result_passed": "Passed",
        "result_failed": "Failed",
        "result_technical_error": "Technical error",
        "col_id": "ID",
        "col_connector": "Connector",
        "col_field": "Field",
        "col_operator": "Operator",
        "col_expected": "Expected",
        "col_obtained": "Obtained",
        "col_query": "Query",
        "col_result": "Result",
        "col_name": "Name",
        "col_type": "Type",
        "not_displayed_label": "Not displayed",
        # Tabs
        "tab_dashboard": "Results",
        "tab_environment": "Environment",
        "tab_timeline": "Timeline",
        "banner_generated_at_prefix": "Generated on",
        # Dashboard — overall status
        "status_reprovado": "FAILED",
        "status_aguardando": "AWAITING VALIDATION",
        "status_aprovado": "APPROVED",
        "dashboard_final_result_label": "Final Result",
        "dashboard_total_label": "Scenarios",
        "legend_passed": "Passed",
        "legend_failed": "Failed",
        "legend_awaiting": "Awaiting",
        "empty_state_no_scenarios": "No scenarios in this execution record.",
        # Mini-cards / grouping
        "mini_cards_title": "Scenarios by group",
        "grouping_label": "Group by:",
        "grouping_folder": "Folder",
        "grouping_feature": "Feature",
        # Filters
        "filter_approved": "Approved",
        "filter_failed": "Failed",
        "filter_awaiting": "Awaiting",
        "search_placeholder": "Search scenario…",
        "active_filter_prefix": "Filtering:",
        "clear_filter_label": "Clear",
        "group_counts_format": "{total} scenarios · {passed} passed · {failed} failed",
        # Scenario detail sections
        "section_requisicao": "Request",
        "section_resposta": "Response",
        "section_verificacoes": "API checks",
        "section_validacao": "Validation",
        "correlation_id_label": "Correlation id",
        "headers_label": "Headers",
        "copy_label": "Copy",
        "scenario_description_label": "Description",
        "no_checks_placeholder": "No API checks configured for this scenario.",
        "validation_pending_placeholder": "Awaiting a validation round.",
        "rounds_count_format": "({count} rounds)",
        "round_label_format": "Round {index}",
        # Environment view
        "env_identificacao_title": "Identification",
        "env_field_environment": "Environment",
        "env_field_timezone": "Timezone",
        "env_field_language": "Report language",
        "env_field_execution_id": "Execution id",
        "env_field_thomas_version": "Thomas version",
        "env_field_start": "Started at",
        "env_api_title": "API under test",
        "env_field_base_url": "Base URL",
        "env_field_timeout": "Timeout",
        "env_field_ssl_verify": "SSL verify",
        "env_ssl_yes": "Yes",
        "env_ssl_no": "No",
        "env_field_collected_at": "Collected at",
        "env_field_info_url": "Address",
        "env_services_title": "Information services",
        "env_connectors_title": "Connectors",
        "view_details_label": "view details",
        "env_variables_title": "Prepared variables",
        "env_var_col_name": "Variable",
        "env_var_col_value": "Value",
        "reveal_label": "show",
        "hide_label": "hide",
        "env_signature_title": "Execution record signature",
        "env_no_headers": "No custom headers configured.",
        # Timeline
        "timeline_title": "Timeline",
        "timeline_gantt_label": "Gantt",
        "timeline_log_label": "Log",
        "timeline_event_request": "Request dispatched",
        "timeline_event_response": "Response received",
        "timeline_event_round": "Validation round",
        "timeline_event_service": "Service collected",
        "timeline_services_row_label": "Information services",
        "timeline_latency_title": "Request latency",
        "timeline_latency_avg": "Average",
        "timeline_latency_p95": "P95",
        "timeline_latency_max": "Maximum",
        "empty_state_no_latency": "No requests with a valid response to measure latency.",
    },
    "pt": {
        "report_title": "Relatório de Testes",
        "dark_mode_toggle": "Modo escuro",
        "no_value_placeholder": "—",
        "result_passed": "Aprovado",
        "result_failed": "Reprovado",
        "result_technical_error": "Erro técnico",
        "col_id": "ID",
        "col_connector": "Conector",
        "col_field": "Campo",
        "col_operator": "Operador",
        "col_expected": "Esperado",
        "col_obtained": "Obtido",
        "col_query": "Consulta",
        "col_result": "Resultado",
        "col_name": "Nome",
        "col_type": "Tipo",
        "not_displayed_label": "Não exibido",
        # Tabs
        "tab_dashboard": "Resultados",
        "tab_environment": "Ambiente",
        "tab_timeline": "Timeline",
        "banner_generated_at_prefix": "Gerado em",
        # Dashboard — overall status
        "status_reprovado": "REPROVADO",
        "status_aguardando": "AGUARDANDO VALIDAÇÃO",
        "status_aprovado": "APROVADO",
        "dashboard_final_result_label": "Resultado Final",
        "dashboard_total_label": "Cenários",
        "legend_passed": "Aprovados",
        "legend_failed": "Falhas",
        "legend_awaiting": "Aguardando",
        "empty_state_no_scenarios": "Nenhum cenário neste registro de execução.",
        # Mini-cards / grouping
        "mini_cards_title": "Cenários por grupo",
        "grouping_label": "Agrupar por:",
        "grouping_folder": "Pasta",
        "grouping_feature": "Funcionalidade",
        # Filters
        "filter_approved": "Aprovados",
        "filter_failed": "Falhas",
        "filter_awaiting": "Aguardando",
        "search_placeholder": "Buscar cenário…",
        "active_filter_prefix": "Filtrando:",
        "clear_filter_label": "Limpar",
        "group_counts_format": "{total} cenários · {passed} aprovados · {failed} falhas",
        # Scenario detail sections
        "section_requisicao": "Requisição",
        "section_resposta": "Resposta",
        "section_verificacoes": "Verificações da API",
        "section_validacao": "Validação",
        "correlation_id_label": "ID de correlação",
        "headers_label": "Headers",
        "copy_label": "copiar",
        "scenario_description_label": "Descrição",
        "no_checks_placeholder": "Nenhuma verificação de API configurada para este cenário.",
        "validation_pending_placeholder": "Aguardando execução de rodada de validação.",
        "rounds_count_format": "({count} execuções)",
        "round_label_format": "Execução {index}",
        # Environment view
        "env_identificacao_title": "Identificação",
        "env_field_environment": "Ambiente",
        "env_field_timezone": "Fuso horário",
        "env_field_language": "Idioma do relatório",
        "env_field_execution_id": "ID de execução",
        "env_field_thomas_version": "Versão The Thomas",
        "env_field_start": "Início",
        "env_api_title": "API sob teste",
        "env_field_base_url": "Base URL",
        "env_field_timeout": "Timeout",
        "env_field_ssl_verify": "SSL verify",
        "env_ssl_yes": "Sim",
        "env_ssl_no": "Não",
        "env_field_collected_at": "Coletado em",
        "env_field_info_url": "Endereço",
        "env_services_title": "Serviços de informação",
        "env_connectors_title": "Conectores",
        "view_details_label": "ver detalhes",
        "env_variables_title": "Variáveis preparatórias",
        "env_var_col_name": "Variável",
        "env_var_col_value": "Valor",
        "reveal_label": "mostrar",
        "hide_label": "ocultar",
        "env_signature_title": "Assinatura do registro de execução",
        "env_no_headers": "Nenhum header customizado configurado.",
        # Timeline
        "timeline_title": "Timeline",
        "timeline_gantt_label": "Gantt",
        "timeline_log_label": "Log",
        "timeline_event_request": "Requisição disparada",
        "timeline_event_response": "Resposta recebida",
        "timeline_event_round": "Rodada de validação",
        "timeline_event_service": "Serviço coletado",
        "timeline_services_row_label": "Serviços de informação",
        "timeline_latency_title": "Latência das requisições",
        "timeline_latency_avg": "Média",
        "timeline_latency_p95": "P95",
        "timeline_latency_max": "Máxima",
        "empty_state_no_latency": "Nenhuma requisição com resposta válida para medir latência.",
    },
}
